apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Graphite

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
- name: Graphite
  type: graphite
  access: proxy
  url: http://graphite:8080
  isDefault: false
  version: 1
  editable: true
